import type { Metadata } from "next";
import "@/app/globals.css";
import { Sidebar } from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen bg-[#141414] text-white">
      <Sidebar />
      <main className="md:ml-20">{children}</main>
    </div>
  );
}
