import type { Metadata } from "next";
import "@/app/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-[#141414] text-white">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
